const soklinData = [
  { nama: 'Surfaktan (LAS, SLES, Alkohol Etoksilat)', rumus: 'LAS · SLES · AE', kat: 'surfaktan', katLabel: 'Surfaktan',
    senyawa: 'Natrium alkil benzena sulfonat, Natrium lauril eter sulfat, Alkohol etoksilat',
    fungsi: 'Menurunkan tegangan permukaan air, mengangkat kotoran dan noda dari serat kain.' },
  { nama: 'Builder (STPP & Zeolit)', rumus: 'STPP · Zeolit', kat: 'builder', katLabel: 'Builder',
    senyawa: 'Sodium Tri Poly Phosphate, Zeolit',
    fungsi: 'Menonaktifkan mineral penyebab kesadahan air, meningkatkan efisiensi surfaktan.' },
  { nama: 'Senyawa Antibakteri', rumus: '~0,12%', kat: 'antibakteri', katLabel: 'Antibakteri',
    senyawa: 'Senyawa antibakteri aktif',
    fungsi: 'Membunuh bakteri pada pakaian sehingga pakaian lebih higienis.' },
  { nama: 'Natrium Hipoklorit', rumus: 'NaClO ~2,25%', kat: 'pemutih', katLabel: 'Pemutih',
    senyawa: 'Natrium hipoklorit (varian tertentu)',
    fungsi: 'Memutihkan pakaian dan menghilangkan noda membandel.' },
  { nama: 'Sodium Sulfat', rumus: 'Na₂SO₄', kat: 'filler', katLabel: 'Filler',
    senyawa: 'Sodium sulfat',
    fungsi: 'Menambah volume produk dan membantu kelarutan komponen lain.' },
  { nama: 'Aditif & Enzim', rumus: 'Enzim · CMC', kat: 'aditif', katLabel: 'Aditif',
    senyawa: 'Enzim, Carboxy Methyl Cellulose, pewangi, pewarna',
    fungsi: 'Meningkatkan daya cuci, mencegah noda menempel kembali, dan memberikan aroma wangi.' },
];
